#!/bin/sh

# Minimal gradlew script to trigger gradle download if not present
# In a real project, this is generated by 'gradle wrapper'

if [ ! -d "gradle/wrapper" ]; then
    mkdir -p gradle/wrapper
fi

# Note: This is a placeholder. In a real GitHub repo, 
# you should run 'gradle wrapper' locally and commit the resulting files.
# For this environment, I'll provide the configuration.

./gradlew assembleDebug
